# coding: utf-8

"""
    minimal-sample-program

    desc

    The version of the OpenAPI document: 33
    Contact: civiform-dev@exygy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.programs_api import router as ProgramsApiRouter

app = FastAPI(
    title="minimal-sample-program",
    description="desc",
    version="33",
)

app.include_router(ProgramsApiRouter)
